"""Redefining dislikes model

Revision ID: 657fba9ac737
Revises: 49ca69b522a4
Create Date: 2022-05-08 23:55:18.659083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657fba9ac737'
down_revision = '49ca69b522a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('pitch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dislike')
    # ### end Alembic commands ###
